version = "pjmai-0.1.0"

[[project]]
name = "webapp"

[project.action]
file_or_dir = "~/code/webapp"

[[project]]
name = "pjmai-rs"

[project.action]
file_or_dir = "~/github/sw-cli-tools/pjmai-rs"

[[project]]
name = "api"

[project.action]
file_or_dir = "~/code/api"
