version = "pjmai-0.1.0"

[[project]]
name = "rtt1"

[project.action]
file_or_dir = "~/github/wrightmikea/rtt1"

[[project]]
name = "pjmai"

[project.action]
file_or_dir = "~/github/wrightmikea/pjmai/.pjmairc"

[[project]]
name = "mr"

[project.action]
file_or_dir = "/home/mike/github/wrightmikea/mono-rust/"
